"""Number entity definitions for midnite_classic integration."""

from __future__ import annotations

from .entity_definitions import NumberDefinition

NUMBER_DEFINITIONS = [
    # Battery voltage settings - using correct register addresses from midnite-registers.json.txt
    NumberDefinition(
        key="absorb_voltage",
        name="Absorb Voltage",
        register_group="settings",
        register_address=4149,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=40.0,
        max_value=65.0,
        step=0.1,
        device_class="voltage",
        unit="V",
        precision=1,
    ),
    NumberDefinition(
        key="float_voltage",
        name="Float Voltage",
        register_group="settings",
        register_address=4150,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=40.0,
        max_value=65.0,
        step=0.1,
        device_class="voltage",
        unit="V",
        precision=1,
    ),
    NumberDefinition(
        key="equalize_voltage",
        name="Equalize Voltage",
        register_group="settings",
        register_address=4151,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=40.0,
        max_value=65.0,
        step=0.1,
        device_class="voltage",
        unit="V",
        precision=1,
    ),
    # Current settings
    NumberDefinition(
        key="absorb_current_limit",
        name="Absorb Current Limit",
        register_group="settings",
        register_address=4153,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=0.0,
        max_value=200.0,
        step=1.0,
        device_class="current",
        unit="A",
    ),
    NumberDefinition(
        key="float_current_limit",
        name="Float Current Limit",
        register_group="settings",
        register_address=4154,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=0.0,
        max_value=200.0,
        step=1.0,
        device_class="current",
        unit="A",
    ),
    # Time settings - using correct register addresses from midnite-registers.json.txt
    NumberDefinition(
        key="absorb_time",
        name="Absorb Time",
        register_group="time_settings",
        register_address=4139,
        formula="value / 60.0",
        write_formula="int(value * 60)",
        min_value=0.0,
        max_value=720.0,  # 12 hours in minutes
        step=1.0,
        device_class="duration",
        unit="minutes",
    ),
    NumberDefinition(
        key="equalize_time",
        name="Equalize Time",
        register_group="time_settings",
        register_address=4143,
        formula="value / 60.0",
        write_formula="int(value * 60)",
        min_value=0.0,
        max_value=720.0,  # 12 hours in minutes
        step=1.0,
        device_class="duration",
        unit="minutes",
    ),
    NumberDefinition(
        key="equalize_days",
        name="Equalize Days",
        register_group="time_settings",
        register_address=4145,
        formula="value",
        write_formula="int(value)",
        min_value=0,
        max_value=365,
        step=1,
    ),
    # Temperature settings
    NumberDefinition(
        key="temp_compensation",
        name="Temperature Compensation",
        register_group="settings",
        register_address=4155,
        formula="value / 10.0",
        write_formula="int(value * 10)",
        min_value=-20.0,
        max_value=20.0,
        step=1.0,
        device_class="temperature",
        unit="%/°C",
    ),
    # Network settings - DISABLED: Using unsupported 5-digit register addresses
    # NumberDefinition(
    #     key="modbus_timeout",
    #     name="Modbus Timeout",
    #     register_group="network",
    #     register_address=20496,
    #     formula="value / 10.0",
    #     write_formula="int(value * 10)",
    #     min_value=0.5,
    #     max_value=30.0,
    #     step=0.5,
    #     device_class="duration",
    #     unit="seconds",
    # ),
]

# Total: 9 number entities defined
